app/models.py
from enum import unique
from operator import index

from sqlalchemy.orm import backref
from . import db
from flask_login import UserMixin, current_user
from . import login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from datetime import datetime, time

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)




class User(UserMixin,db.Model):

    '''class user with its properties'''

    __tablename__ = 'users'

    #nullable = False tells SQLAlchemy to create the column as NOT NULL

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),unique=True,nullable = False)
    email = db.Column(db.String(255),unique=True,nullable = False)
    pass_secure = db.Column(db.String(255),nullable = False)
    profile_pic_path = db.Column(db.String())
    bio = db.Column(db.String(255))


    post = db.relationship('Pitch', backref = 'user', lazy = 'dynamic')
    comment = db.relationship('Comment', backref = 'user', lazy = 'dynamic')
    upvote = db.relationship('Upvote', backref = 'user', lazy = 'dynamic')
    downvote = db.relationship('Downvote', backref = 'user', lazy = 'dynamic')

    
    @property
    def password(self):
        raise AttributeError('You can not access the password attribute')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def delete_user(self):
        db.session.delete(self)
        db.session.commit()


    def __repr__(self):
        return f'User {self.username}'



class Pitch(db.Model):
    '''class pitch and its properties'''

    __tablename__ = 'pitches'

    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    pitch = db.Column(db.Text(), nullable = False)
    time_posted = db.Column(db.DateTime, default = datetime.utcnow)
    category_of_the_pitch = db.Column(db.String(150), index = True, nullable = False)
    comments = db.relationship('Comment',backref='pitch',lazy='dynamic')
    upvote = db.relationship('Upvote', backref = 'pitch', lazy = 'dynamic')
    downvote = db.relationship('Downvote', backref = 'pitch', lazy = 'dynamic')



    @classmethod
    def fetch_pitches(cls, id):
        pitches = Pitch.query.order_by(post_id= id).desc().all()
        return pitches

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    def delete_pitch(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'Pitch {self.pitch}'



class Comment(db.Model):
    '''class comment and its properties'''

    __tablename__ = 'comment'

    id = db.Column(db.Integer, primary_key = True)
    comment = db.Column(db.Text(), nullable = False)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable = False)
    post_id = db.Column(db.Integer,db.ForeignKey('pitches.id'),nullable = False)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def fetch_comments(cls,id):
        comments = Comment.query.filter_by(post_id=id).all()

        return comments

    def __repr__(self):
        return f'comment:{self.comment}'

class Upvote(db.Model):

    __tablename__ = 'upvotes'

    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer,db.ForeignKey('pitches.id'))

    def save_upvotes(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def fetch_by_post(cls,id):
        upvote_by_post=Upvote.query.filter_by(post_id=id).all()
        return upvote_by_post

    def __repr__(self) -> str:
        return f'Upvote{self.user_id}:{self.post_id}'

class Downvote(db.Model):

    __tablename__ = 'downvotes'

    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer,db.ForeignKey('pitches.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def fetch_downvotes(cls,id):
        downvote = Downvote.query.filter_by(post_id = id).all()
        return downvote

    def __repr__(self) -> str:
        return f'{self.user_id}:{self.post_id}'





    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, TextAreaField, SubmitField, ValidationError
from wtforms.validators import Required,Email,EqualTo

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about yourself.',validators=[Required()])
    submit = SubmitField('Submit')

class PitchForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    category = SelectField('Category', choices=[('Job','Job'),('Advertisement','Advertisement')],validators=[Required()])
    post = TextAreaField('write your pitch here...', validators=[Required()])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    comment = TextAreaField('Care to leave a comment here?',validators=[Required()])
    submit = SubmitField('Post Comment')

app/__init__.py
from flask import Flask
import config
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

#Initializing Flask Extensions
bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)


    #configure UploadSet
    configure_uploads(app,photos)


    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # Registering the main blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Registering the auth blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    # setting config
    

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors

app/main/views.py
from flask import render_template, request, redirect, url_for, abort, flash
from . import main
from ..models import User, Pitch, Comment, Upvote, Downvote
from .. import db,photos
from flask_login import login_required, current_user
from .forms import PitchForm, UpdateProfile, CommentForm

@main.route('/')
def main_page():
    '''this is my main page where a user will either login or register to access the site'''

    return redirect(url_for('auth.login'))

@main.route('/login')
def landing_page():
    title = 'Mathwiti | Login'
    return render_template('index.html', title = title)

@main.route('/profile')
def profile_page():
    title = 'Mathwiti | Profile'
    return render_template('profile/profile.html', title = title)

@main.route('/job')
def job_page():
    title = 'Mathwiti | Job'
    pitch = Pitch.query.filter_by(category_of_the_pitch = 'Job').all()
    return render_template('job_page.html', title = title, pitch=pitch)

@main.route('/pitch/new', methods = ['GET','POST'])
@login_required
def new_pitch():
    title = 'Mathwiti | Create Pitch'
    job_new = PitchForm()
    if job_new.validate_on_submit():
        kichwa = job_new.title.data
        post = job_new.post.data
        category = job_new.category.data
        owner_id = current_user
        new_job = Pitch(user_id=current_user._get_current_object().id,pitch=post,category_of_the_pitch=category)
        db.session.add(new_job)
        db.session.commit()
        return redirect(url_for('main.profile_page'))
    return render_template('newPitch.html', title = title,job_new=job_new)

@main.route('/advert')
def advert():
    title = "Mathwiti | Advertisements"
    pitch = Pitch.query.filter_by(category_of_the_pitch = 'Advertisement').all()
    return render_template("advertisment.html", title= title, pitch=pitch)

app/templates/advertisment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="card">
        {% for x in pitch %}
        <div class="card-title">{{x.pitch}}</div>
        <span>Posted at: {{x.time_posted}}</span>
        {% endfor %}
    </div>
    
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title}}</title>
    {% block styles %}

    <!-- Bootstrap CDN -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- Font Awesome Icons CDN -->
    <link
      href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css"
      rel="stylesheet"
    />
    <!-- CSS link -->
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='css/styles.css')}}"
    />
    <!-- Google Font Popper-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
      rel="stylesheet"
    />
    {% endblock %}
  </head>
  <body>
    <!-- Navbar Block -->
    {% block navbar %} {% include 'navbar.html' %} {% endblock %}
    <div class="container-fluid">{% block content %} {% endblock %}</div>
  </body>
</html>

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<div class="row">
    <div class="card">
      <div class="card-body text-center">
        <h4><a>{{pitch.title}}</a></h4>
        <h5 class="card-text text-center">{{pitch.description}}.</h5>
      </div>
    </div>
  <div class="container">
    <div class="row">
      <div class="jumbotron bg-light">
        {{wtf.quick_form(form)}}
      </div>
    </div>
  </div>                  
  <hr>
  <div class="container">
    <h2 style=" text-align: center; font-weight: bold; margin-bottom: 40px;">Comments</h2>
    <div class="col-md-6">

    </div>         
  </div>      
</div>
{% endblock%}

app/templates/job.html
  
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="card">
        {% for x in pitch %}
        <div class="card-title">{{x.pitch}}</div>
        <span>Posted at: {{x.time_posted}}</span>
        {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/job_page.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="card">
        {% for x in pitch %}
        <div class="card-title">{{x.pitch}}</div>
        <span>Posted at: {{x.time_posted}}</span>
        {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-xl navbar-dark bg-dark">
  <div class="container-fluid" id="container">
    <div class="col-10">
      <a class="navbar-brand">
        <h1>Mathwiti</h1>
      </a>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" href="{{url_for('main.profile_page')}}">Home</a>
          <a class="nav-link" href="{{url_for('main.job_page')}}">Job</a>
          <a class="nav-link" href="{{url_for('main.advert')}}">Advertisment</a>
          <a class="nav-link" href="{{url_for('main.new_pitch')}}">Add Pitch</a>

        </div>
      </div>
    </div>
    <div class="col-2">
      <button type="button" class="btn btn-outline-dark me-2">
        <a
          
          style="color: #f5245f; text-decoration: none"
          ><i class="bi bi-person-fill"></i>{{current_user.username}}</a
        >
      </button>
      <button type="button" class="btn btn-outline-dark me-2">
        <a
          href="{{url_for('auth.logout')}}"
          style="text-decoration: none; color: #f5245f"
          >Logout</a
        >
      </button>
    </div>
  </div>
</nav>

app/templates/newPitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{ wtf.quick_form(job_new)}}
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}
<h1></h1>